// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjtn4rEvGtO8SRmCz9e5OyvqkFbLhhayc',
    appId: '1:73438566042:web:60d611de889a6887c6b123',
    messagingSenderId: '73438566042',
    projectId: 'cemberapp-2a101',
    authDomain: 'cemberapp-2a101.firebaseapp.com',
    databaseURL: 'https://cemberapp-2a101-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cemberapp-2a101.firebasestorage.app',
    measurementId: 'G-1ZLQWNS1JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgAkMosmaKbDVOjPsIUCfvsppEft36aiU',
    appId: '1:73438566042:android:33bf5e0d716de9e5c6b123',
    messagingSenderId: '73438566042',
    projectId: 'cemberapp-2a101',
    databaseURL: 'https://cemberapp-2a101-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cemberapp-2a101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZMo1Grc6B1LEFzCb3x_SpJPcndVwVFAQ',
    appId: '1:73438566042:ios:4c6e014008aa96cfc6b123',
    messagingSenderId: '73438566042',
    projectId: 'cemberapp-2a101',
    databaseURL: 'https://cemberapp-2a101-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cemberapp-2a101.firebasestorage.app',
    iosBundleId: 'com.sabri.cember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZMo1Grc6B1LEFzCb3x_SpJPcndVwVFAQ',
    appId: '1:73438566042:ios:4c6e014008aa96cfc6b123',
    messagingSenderId: '73438566042',
    projectId: 'cemberapp-2a101',
    databaseURL: 'https://cemberapp-2a101-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cemberapp-2a101.firebasestorage.app',
    iosBundleId: 'com.sabri.cember',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjtn4rEvGtO8SRmCz9e5OyvqkFbLhhayc',
    appId: '1:73438566042:web:cbb3155ab678d208c6b123',
    messagingSenderId: '73438566042',
    projectId: 'cemberapp-2a101',
    authDomain: 'cemberapp-2a101.firebaseapp.com',
    databaseURL: 'https://cemberapp-2a101-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cemberapp-2a101.firebasestorage.app',
  );
}
